name: Build OverlayDetect

on:
  workflow_dispatch:
  push:
    paths:
      - overlay_detect.cpp

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Build overlay_detect.exe
        run: g++ overlay_detect.cpp -o overlay_detect.exe -lpsapi -static

      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: OverlayDetectEXE
          path: overlay_detect.exe
